name: Lint, test, and scan Helm charts
on:
  pull_request:
    branches:
      - master
      - release/**
  workflow_dispatch:
jobs:
  lint-test-scan:
    uses: Cray-HPE/.github/.github/workflows/charts-lint-test-scan.yml@main
    with:
      lint-charts: ${{ github.event_name == 'pull_request' }}
      ct-config: |
        chart-dirs:
          - kubernetes
        chart-repos:
          - cray-algol60=https://artifactory.algol60.net/artifactory/csm-helm-charts
        validate-maintainers: false
      scan-chart-snyk-args: "--severity-threshold=high"
      scan-image-snyk-args: "--severity-threshold=high"
      test-charts: false
      scan-images: false
    secrets:
      snyk-token: ${{ secrets.SNYK_TOKEN }}

